texfun={
    'sqrt':         r'\sqrt{%s}',
    'sum':         r'{\sum_%s^%s %s}',
    }

texmod={
    'vec':          r'\boldsymbol{%s}',
    'bar':          r'\bar{%s}',
    'star':         r'%s^*',
    'tilde':        r'\tilde{%s}',
    }

texsym={
'alpha'         :r'\alpha',
'beta'          :r'\beta',
'gamma'         :r'\gamma',
'delta'         :r'\delta',
'epsilon'       :r'\epsilon',
'varepsilon'    :r'\varepsilon',
'zeta'          :r'\zeta',
'eta'           :r'\eta',
'Lambda'        :r'\Lambda',
'Xi'            :r'\Xi',
'Pi'            :r'\Pi',
'Psi'           :r'\Psi',
'Omega'         :r'\Omega',
'Sigma'         :r'\Sigma',
'Upsilon'       :r'\Upsilon',
'Phi'           :r'\Phi',
'Gamma'         :r'\Gamma',
'Delta'         :r'\Delta',
'Theta'         :r'\Theta',
'tau'           :r'\tau',
'upsilon'       :r'\upsilon',
'phi'           :r'\phi',
'varphi'        :r'\varphi',
'chi'           :r'\chi',
'psi'           :r'\psi',
'omega'         :r'\omega',
'pi'            :r'\pi',
'varpi'         :r'\varpi',
'rho'           :r'\rho',
'varrho'        :r'\varrho',
'sigma'         :r'\sigma',
'varsigma'      :r'\varsigma',
'thetao'        :r'\thetao',
'vartheta'      :r'\vartheta',
'iota'          :r'\iota',
'kappa'         :r'\kappa',
'lambda'        :r'\lambda',
'mu'            :r'\mu',
'nu'            :r'\nu',
'xi'            :r'\xi',
    }
