

sussix.so: sussix4drivexxNoO.f
	/afs/cern.ch/eng/sl/lintrack/Python-2.5_32bit/Python-2.5_32bit/bin/python /afs/cern.ch/eng/sl/lintrack/Python-2.5_32bit/Python-2.5_32bit/bin/f2py2.5 -c -m sussix4drivexxNoO32 sussix4drivexxNoO.f
